---
# tasks file for sa-ruby
  - debug: msg="Tasks section"

  - name: Playbook | package dependencies + cache update
    apt: pkg={{ item }} state=present force="yes"  update_cache="yes"
    with_items: "{{needed_packages}}"
    become: yes

  - include: 'ch_ruby.yml'

  - include: 'ruby_install.yml'

  - include: 'ruby.yml'

  - include: 'nginx_passenger.yml'
    when: option_install_nginx_passenger

  - include: 'ruby_app_stub.yml'
    when: option_install_app 
